appCfgPath: ${APP_CONFIG_PATH:/config}

spring:
  application:
    name: otus-dz-2
  config:
    import:
      - file:${appCfgPath}/db.yaml

management:
  endpoints:
    web:
      base-path: ""

server:
  port: ${APP_HTTP_PORT:8000}