appCfgPath: ${APP_CONFIG_PATH:/config}

spring:
  application:
    name: otus-dz-2
  config:
    import:
      - file:${appCfgPath}/db.yaml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${APP_HTTP_PORT:8000}